
#Day; 

DELIMITER $$
DROP PROCEDURE IF EXISTS update_partition  $$
CREATE PROCEDURE update_partition ()
BEGIN
DECLARE PARTITIONDATE int;
DECLARE PARTITIONDATEID int;

SET PARTITIONDATE = DATE_FORMAT(now(),"%Y-%m-%d");

SELECT (date_id - 1) INTO PARTITIONDATEID 
FROM dim_date
WHERE date = PARTITIONDATE; 


ALTER TABLE agg_event_resource_world_day TRUNCATE PARTITION current;

ALTER TABLE agg_event_resource_world_day REORGANIZE PARTITION current,previous INTO (
  PARTITION previous VALUES LESS THAN ('PARTITIONDATEID'),
  PARTITION current VALUES LESS THAN MAXVALUE);
  
END $$



#Week;

DELIMITER $$
DROP PROCEDURE IF EXISTS update_partition  $$
CREATE PROCEDURE update_partition ()
BEGIN
DECLARE PARTITIONDATE int;
DECLARE PARTITIONDATEID int;

SET PARTITIONDATE = DATE_FORMAT(now(),"%Y-%m-%d");

SELECT (week_date_id) INTO PARTITIONDATEID 
FROM dim_date
WHERE date = PARTITIONDATE; 


ALTER TABLE agg_event_resource_world_week TRUNCATE PARTITION current;

ALTER TABLE agg_event_resource_world_week REORGANIZE PARTITION current,previous INTO (
  PARTITION previous VALUES LESS THAN ('PARTITIONDATEID'),
  PARTITION current VALUES LESS THAN MAXVALUE);
  
END $$


#Month;

DELIMITER $$
DROP PROCEDURE IF EXISTS update_partition  $$
CREATE PROCEDURE update_partition ()
BEGIN
DECLARE PARTITIONDATE int;
DECLARE PARTITIONDATEID int;

SET PARTITIONDATE = DATE_FORMAT(now(),"%Y-%m-%d");

SELECT (month_date_id) INTO PARTITIONDATEID 
FROM dim_date
WHERE date = PARTITIONDATE; 


ALTER TABLE agg_event_resource_world_month TRUNCATE PARTITION current;

ALTER TABLE agg_event_resource_world_month REORGANIZE PARTITION current,previous INTO (
  PARTITION previous VALUES LESS THAN ('PARTITIONDATEID'),
  PARTITION current VALUES LESS THAN MAXVALUE);
  
END $$


#Year;

DELIMITER $$
DROP PROCEDURE IF EXISTS update_partition  $$
CREATE PROCEDURE update_partition ()
BEGIN
DECLARE PARTITIONDATE int;
DECLARE PARTITIONDATEID int;

SET PARTITIONDATE = DATE_FORMAT(now(),"%Y-%m-%d");

SELECT (month_date_id) INTO PARTITIONDATEID 
FROM dim_date
WHERE date = PARTITIONDATE; 


ALTER TABLE agg_event_resource_world_year TRUNCATE PARTITION current;

ALTER TABLE agg_event_resource_world_year REORGANIZE PARTITION current,previous INTO (
  PARTITION previous VALUES LESS THAN ('PARTITIONDATEID'),
  PARTITION current VALUES LESS THAN MAXVALUE);
  
END $$

