DELIMITER $$
DROP PROCEDURE IF EXISTS update_partition  $$
CREATE PROCEDURE update_partition ()
BEGIN
DECLARE PARTITIONDATE varchar;
DECLARE PARTITIONDATEID int;
DECLARE PARTITIONWEEKDATEID int;
DECLARE PARTITIONMONTHDATEID int;
DECLARE PARTITIONYEARDATEID int;
SET PARTITIONDATE = DATE_FORMAT(now(),"%Y-%m-%d");

SELECT (date_id - 1) INTO PARTITIONDATEID FROM dim_date WHERE date = PARTITIONDATE; 
SELECT week_date_id  INTO PARTITIONWEEKDATEID FROM dim_date WHERE date = PARTITIONDATE; 
SELECT month_date_id INTO PARTITIONMONTHDATEID FROM dim_date WHERE date = PARTITIONDATE; 
SELECT year_date_id  INTO PARTITIONYEARDATEID FROM dim_date WHERE date = PARTITIONDATE; 

  ALTER TABLE agg_event_resource_world_day TRUNCATE PARTITION current;
  ALTER TABLE agg_event_resource_world_day REORGANIZE PARTITION current,previous INTO (
  PARTITION previous VALUES LESS THAN (PARTITIONDATEID),
  PARTITION current VALUES LESS THAN MAXVALUE);

  IF(PARTITIONDATEID = PARTITIONWEEKDATEID) THEN
      ALTER TABLE agg_event_resource_world_week REORGANIZE PARTITION current,previous INTO (
      PARTITION previous VALUES LESS THAN (PARTITIONWEEKDATEID),
      PARTITION current VALUES LESS THAN MAXVALUE);
  ELSE 
    ALTER TABLE agg_event_resource_world_week TRUNCATE PARTITION current;
  END IF;
 
  IF(PARTITIONDATEID = PARTITIONMONTHDATEID) THEN
      ALTER TABLE agg_event_resource_world_month REORGANIZE PARTITION current,previous INTO (
      PARTITION previous VALUES LESS THAN (PARTITIONMONTHDATEID),
      PARTITION current VALUES LESS THAN MAXVALUE);
  ELSE
      ALTER TABLE agg_event_resource_world_month TRUNCATE PARTITION current;
  END IF;
  
  IF(PARTITIONDATEID = PARTITIONYEARDATEID) THEN
	ALTER TABLE agg_event_resource_world_year REORGANIZE PARTITION current,previous INTO (
	PARTITION previous VALUES LESS THAN (PARTITIONYEARDATEID),
	PARTITION current VALUES LESS THAN MAXVALUE);
  ELSE
    ALTER TABLE agg_event_resource_world_year TRUNCATE PARTITION current;
  END IF;

CALL update_partition();
  
END $$

delimiter ;
call update_partition();

